<?php
// Auto-generated from: Shipments LEADHANDKENT2 2026-09-30T10_57_04.xlsx on 2026-09-30 10:58:32

$cancelled_sh = ['SH54819933'];

$order_data = [];
$order_data['SH54952494'] = [
    [
        'document' => 'S94579',
        'header_ref' => 'SH54952494',
        'status' => 'SCANCOMP',
        'date_to_ship' => '9/30/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Medline Industries',
        'ship_to_city' => 'Montgomery',
        'ship_to_state' => 'NY',
        'ship_to_ref' => '',
        'qty_ordered' => 45,
        'qty_committed' => 45,
        'warehouse' => 'KENT2',
    ],
    [
        'document' => 'S94586',
        'header_ref' => 'SH54952494',
        'status' => 'SCANCOMP',
        'date_to_ship' => '9/30/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Medline Industries',
        'ship_to_city' => 'Montgomery',
        'ship_to_state' => 'NY',
        'ship_to_ref' => '',
        'qty_ordered' => 35,
        'qty_committed' => 35,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54937251'] = [
    [
        'document' => 'S94767',
        'header_ref' => 'SH54937251',
        'status' => 'PICK PRTD',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon',
        'ship_to_city' => 'Huntley',
        'ship_to_state' => 'IL',
        'ship_to_ref' => '',
        'qty_ordered' => 137,
        'qty_committed' => 137,
        'warehouse' => 'KENT2',
    ],
    [
        'document' => 'S94861',
        'header_ref' => 'SH54937251',
        'status' => 'PICK PRTD',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon',
        'ship_to_city' => 'Huntley',
        'ship_to_state' => 'IL',
        'ship_to_ref' => '',
        'qty_ordered' => 200,
        'qty_committed' => 200,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54957687'] = [
    [
        'document' => 'S94768',
        'header_ref' => 'SH54957687',
        'status' => 'SCANCOMP',
        'date_to_ship' => '9/30/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Medline Industries',
        'ship_to_city' => 'Southaven',
        'ship_to_state' => 'MS',
        'ship_to_ref' => '',
        'qty_ordered' => 200,
        'qty_committed' => 200,
        'warehouse' => 'KENT2',
    ],
    [
        'document' => 'S94769',
        'header_ref' => 'SH54957687',
        'status' => 'SCANCOMP',
        'date_to_ship' => '9/30/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Medline Industries',
        'ship_to_city' => 'Southaven',
        'ship_to_state' => 'MS',
        'ship_to_ref' => '',
        'qty_ordered' => 218,
        'qty_committed' => 218,
        'warehouse' => 'KENT2',
    ],
    [
        'document' => 'S94770',
        'header_ref' => 'SH54957687',
        'status' => 'SCANCOMP',
        'date_to_ship' => '9/30/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Medline Industries',
        'ship_to_city' => 'Southaven',
        'ship_to_state' => 'MS',
        'ship_to_ref' => '',
        'qty_ordered' => 41800,
        'qty_committed' => 41800,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54957693'] = [
    [
        'document' => 'S94771',
        'header_ref' => 'SH54957693',
        'status' => 'SCANCOMP',
        'date_to_ship' => '9/30/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Medline Industries',
        'ship_to_city' => 'Hammond',
        'ship_to_state' => 'LA',
        'ship_to_ref' => '',
        'qty_ordered' => 63,
        'qty_committed' => 63,
        'warehouse' => 'KENT2',
    ],
    [
        'document' => 'S94772',
        'header_ref' => 'SH54957693',
        'status' => 'SCANCOMP',
        'date_to_ship' => '9/30/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Medline Industries',
        'ship_to_city' => 'Hammond',
        'ship_to_state' => 'LA',
        'ship_to_ref' => '',
        'qty_ordered' => 77,
        'qty_committed' => 77,
        'warehouse' => 'KENT2',
    ],
    [
        'document' => 'S94773',
        'header_ref' => 'SH54957693',
        'status' => 'SCANCOMP',
        'date_to_ship' => '9/30/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Medline Industries',
        'ship_to_city' => 'Hammond',
        'ship_to_state' => 'LA',
        'ship_to_ref' => '',
        'qty_ordered' => 19600,
        'qty_committed' => 19600,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54957697'] = [
    [
        'document' => 'S94774',
        'header_ref' => 'SH54957697',
        'status' => 'SCANCOMP',
        'date_to_ship' => '9/30/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Medline Industries',
        'ship_to_city' => 'Jeffersonville',
        'ship_to_state' => 'IN',
        'ship_to_ref' => '',
        'qty_ordered' => 220,
        'qty_committed' => 220,
        'warehouse' => 'KENT2',
    ],
    [
        'document' => 'S94775',
        'header_ref' => 'SH54957697',
        'status' => 'SCANCOMP',
        'date_to_ship' => '9/30/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Medline Industries',
        'ship_to_city' => 'Jeffersonville',
        'ship_to_state' => 'IN',
        'ship_to_ref' => '',
        'qty_ordered' => 240,
        'qty_committed' => 240,
        'warehouse' => 'KENT2',
    ],
    [
        'document' => 'S94776',
        'header_ref' => 'SH54957697',
        'status' => 'SCANCOMP',
        'date_to_ship' => '9/30/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Medline Industries',
        'ship_to_city' => 'Jeffersonville',
        'ship_to_state' => 'IN',
        'ship_to_ref' => '',
        'qty_ordered' => 86400,
        'qty_committed' => 86400,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54957700'] = [
    [
        'document' => 'S94777',
        'header_ref' => 'SH54957700',
        'status' => 'SCANCOMP',
        'date_to_ship' => '9/30/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Medline Industries',
        'ship_to_city' => 'Wilmer',
        'ship_to_state' => 'TX',
        'ship_to_ref' => '',
        'qty_ordered' => 52,
        'qty_committed' => 52,
        'warehouse' => 'KENT2',
    ],
    [
        'document' => 'S94778',
        'header_ref' => 'SH54957700',
        'status' => 'SCANCOMP',
        'date_to_ship' => '9/30/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Medline Industries',
        'ship_to_city' => 'Wilmer',
        'ship_to_state' => 'TX',
        'ship_to_ref' => '',
        'qty_ordered' => 5600,
        'qty_committed' => 5600,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54957701'] = [
    [
        'document' => 'S94779',
        'header_ref' => 'SH54957701',
        'status' => 'SCANCOMP',
        'date_to_ship' => '9/30/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Medline',
        'ship_to_city' => 'Aurora',
        'ship_to_state' => 'CO',
        'ship_to_ref' => '',
        'qty_ordered' => 18,
        'qty_committed' => 18,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54957708'] = [
    [
        'document' => 'S94780',
        'header_ref' => 'SH54957708',
        'status' => 'SCANCOMP',
        'date_to_ship' => '9/30/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Medline Industries',
        'ship_to_city' => 'Chester',
        'ship_to_state' => 'VA',
        'ship_to_ref' => '',
        'qty_ordered' => 57,
        'qty_committed' => 57,
        'warehouse' => 'KENT2',
    ],
    [
        'document' => 'S94781',
        'header_ref' => 'SH54957708',
        'status' => 'SCANCOMP',
        'date_to_ship' => '9/30/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Medline Industries',
        'ship_to_city' => 'Chester',
        'ship_to_state' => 'VA',
        'ship_to_ref' => '',
        'qty_ordered' => 54,
        'qty_committed' => 54,
        'warehouse' => 'KENT2',
    ],
    [
        'document' => 'S94782',
        'header_ref' => 'SH54957708',
        'status' => 'SCANCOMP',
        'date_to_ship' => '9/30/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Medline Industries',
        'ship_to_city' => 'Chester',
        'ship_to_state' => 'VA',
        'ship_to_ref' => '',
        'qty_ordered' => 2800,
        'qty_committed' => 2800,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54957716'] = [
    [
        'document' => 'S94783',
        'header_ref' => 'SH54957716',
        'status' => 'SCANCOMP',
        'date_to_ship' => '9/30/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Medline Industries',
        'ship_to_city' => 'Auburndale',
        'ship_to_state' => 'FL',
        'ship_to_ref' => '',
        'qty_ordered' => 269,
        'qty_committed' => 269,
        'warehouse' => 'KENT2',
    ],
    [
        'document' => 'S94784',
        'header_ref' => 'SH54957716',
        'status' => 'SCAN START',
        'date_to_ship' => '9/30/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Medline Industries',
        'ship_to_city' => 'Auburndale',
        'ship_to_state' => 'FL',
        'ship_to_ref' => '',
        'qty_ordered' => 300,
        'qty_committed' => 300,
        'warehouse' => 'KENT2',
    ],
    [
        'document' => 'S94785',
        'header_ref' => 'SH54957716',
        'status' => 'PARTIALLY SHORT',
        'date_to_ship' => '9/30/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Medline Industries',
        'ship_to_city' => 'Auburndale',
        'ship_to_state' => 'FL',
        'ship_to_ref' => '',
        'qty_ordered' => 131200,
        'qty_committed' => 38450,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54937303'] = [
    [
        'document' => 'S94786',
        'header_ref' => 'SH54937303',
        'status' => 'PICK PRTD',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Phoenix',
        'ship_to_state' => 'AZ',
        'ship_to_ref' => '',
        'qty_ordered' => 50,
        'qty_committed' => 50,
        'warehouse' => 'KENT2',
    ],
    [
        'document' => 'S94905',
        'header_ref' => 'SH54937303',
        'status' => 'PICK PRTD',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Phoenix',
        'ship_to_state' => 'AZ',
        'ship_to_ref' => '',
        'qty_ordered' => 2,
        'qty_committed' => 2,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54937307'] = [
    [
        'document' => 'S94787',
        'header_ref' => 'SH54937307',
        'status' => 'PICK PRTD',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon',
        'ship_to_city' => 'Greenwood',
        'ship_to_state' => 'IN',
        'ship_to_ref' => '',
        'qty_ordered' => 100,
        'qty_committed' => 100,
        'warehouse' => 'KENT2',
    ],
    [
        'document' => 'S94906',
        'header_ref' => 'SH54937307',
        'status' => 'PICK PRTD',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon',
        'ship_to_city' => 'Greenwood',
        'ship_to_state' => 'IN',
        'ship_to_ref' => '',
        'qty_ordered' => 50,
        'qty_committed' => 50,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54939626'] = [
    [
        'document' => 'S94788',
        'header_ref' => 'SH54939626',
        'status' => 'PICK PRTD',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Medline Industries',
        'ship_to_city' => 'Grayslake',
        'ship_to_state' => 'IL',
        'ship_to_ref' => '',
        'qty_ordered' => 6,
        'qty_committed' => 6,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54942600'] = [
    [
        'document' => 'S94789',
        'header_ref' => 'SH54942600',
        'status' => 'PICK PRTD',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Joliet',
        'ship_to_state' => 'IL',
        'ship_to_ref' => '',
        'qty_ordered' => 150,
        'qty_committed' => 150,
        'warehouse' => 'KENT2',
    ],
    [
        'document' => 'S94863',
        'header_ref' => 'SH54942600',
        'status' => 'PICK PRTD',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Joliet',
        'ship_to_state' => 'IL',
        'ship_to_ref' => '',
        'qty_ordered' => 100,
        'qty_committed' => 100,
        'warehouse' => 'KENT2',
    ],
    [
        'document' => 'S94916',
        'header_ref' => 'SH54942600',
        'status' => 'PICK PRTD',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Joliet',
        'ship_to_state' => 'IL',
        'ship_to_ref' => '',
        'qty_ordered' => 50,
        'qty_committed' => 50,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54943393'] = [
    [
        'document' => 'S94790',
        'header_ref' => 'SH54943393',
        'status' => 'PICK PRTD',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon',
        'ship_to_city' => 'Hazle TWP',
        'ship_to_state' => 'PA',
        'ship_to_ref' => '',
        'qty_ordered' => 50,
        'qty_committed' => 50,
        'warehouse' => 'KENT2',
    ],
    [
        'document' => 'S94867',
        'header_ref' => 'SH54943393',
        'status' => 'PICK PRTD',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon',
        'ship_to_city' => 'Hazle TWP',
        'ship_to_state' => 'PA',
        'ship_to_ref' => '',
        'qty_ordered' => 50,
        'qty_committed' => 50,
        'warehouse' => 'KENT2',
    ],
    [
        'document' => 'S94919',
        'header_ref' => 'SH54943393',
        'status' => 'PICK PRTD',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon',
        'ship_to_city' => 'Hazle TWP',
        'ship_to_state' => 'PA',
        'ship_to_ref' => '',
        'qty_ordered' => 50,
        'qty_committed' => 50,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54947417'] = [
    [
        'document' => 'S94791',
        'header_ref' => 'SH54947417',
        'status' => 'PICK PRTD',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon',
        'ship_to_city' => 'Huntley',
        'ship_to_state' => 'IL',
        'ship_to_ref' => '',
        'qty_ordered' => 50,
        'qty_committed' => 50,
        'warehouse' => 'KENT2',
    ],
    [
        'document' => 'S94921',
        'header_ref' => 'SH54947417',
        'status' => 'PICK PRTD',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon',
        'ship_to_city' => 'Huntley',
        'ship_to_state' => 'IL',
        'ship_to_ref' => '',
        'qty_ordered' => 50,
        'qty_committed' => 50,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54947421'] = [
    [
        'document' => 'S94792',
        'header_ref' => 'SH54947421',
        'status' => 'PICK PRTD',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon',
        'ship_to_city' => 'Hazle TWP',
        'ship_to_state' => 'PA',
        'ship_to_ref' => '',
        'qty_ordered' => 50,
        'qty_committed' => 50,
        'warehouse' => 'KENT2',
    ],
    [
        'document' => 'S94924',
        'header_ref' => 'SH54947421',
        'status' => 'PICK PRTD',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon',
        'ship_to_city' => 'Hazle TWP',
        'ship_to_state' => 'PA',
        'ship_to_ref' => '',
        'qty_ordered' => 50,
        'qty_committed' => 50,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54952137'] = [
    [
        'document' => 'S94847',
        'header_ref' => 'SH54952137',
        'status' => 'PICK PRTD',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon',
        'ship_to_city' => 'Huntley',
        'ship_to_state' => 'IL',
        'ship_to_ref' => '',
        'qty_ordered' => 50,
        'qty_committed' => 50,
        'warehouse' => 'KENT2',
    ],
    [
        'document' => 'S94925',
        'header_ref' => 'SH54952137',
        'status' => 'PICK PRTD',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon',
        'ship_to_city' => 'Huntley',
        'ship_to_state' => 'IL',
        'ship_to_ref' => '',
        'qty_ordered' => 100,
        'qty_committed' => 100,
        'warehouse' => 'KENT2',
    ],
    [
        'document' => 'S94963',
        'header_ref' => 'SH54952137',
        'status' => 'PICK PRTD',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon',
        'ship_to_city' => 'Huntley',
        'ship_to_state' => 'IL',
        'ship_to_ref' => '',
        'qty_ordered' => 300,
        'qty_committed' => 300,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54927140'] = [
    [
        'document' => 'S94848',
        'header_ref' => 'SH54927140',
        'status' => 'PICK PRTD',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Phoenix',
        'ship_to_state' => 'AZ',
        'ship_to_ref' => '',
        'qty_ordered' => 100,
        'qty_committed' => 100,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54927145'] = [
    [
        'document' => 'S94849',
        'header_ref' => 'SH54927145',
        'status' => 'PICK PRTD',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Las Vegas',
        'ship_to_state' => 'NV',
        'ship_to_ref' => '',
        'qty_ordered' => 150,
        'qty_committed' => 150,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54927149'] = [
    [
        'document' => 'S94850',
        'header_ref' => 'SH54927149',
        'status' => 'PICK PRTD',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Rancho Cordova',
        'ship_to_state' => 'CA',
        'ship_to_ref' => '',
        'qty_ordered' => 50,
        'qty_committed' => 50,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54927155'] = [
    [
        'document' => 'S94851',
        'header_ref' => 'SH54927155',
        'status' => 'PICK PRTD',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon',
        'ship_to_city' => 'Florence',
        'ship_to_state' => 'NJ',
        'ship_to_ref' => '',
        'qty_ordered' => 50,
        'qty_committed' => 50,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54927157'] = [
    [
        'document' => 'S94852',
        'header_ref' => 'SH54927157',
        'status' => 'PICK PRTD',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon',
        'ship_to_city' => 'Greenwood',
        'ship_to_state' => 'IN',
        'ship_to_ref' => '',
        'qty_ordered' => 50,
        'qty_committed' => 50,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54932228'] = [
    [
        'document' => 'S94853',
        'header_ref' => 'SH54932228',
        'status' => 'PICK PRTD',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Las Vegas',
        'ship_to_state' => 'NV',
        'ship_to_ref' => '',
        'qty_ordered' => 50,
        'qty_committed' => 50,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54932247'] = [
    [
        'document' => 'S94854',
        'header_ref' => 'SH54932247',
        'status' => 'PICK PRTD',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Rancho Cordova',
        'ship_to_state' => 'CA',
        'ship_to_ref' => '',
        'qty_ordered' => 100,
        'qty_committed' => 100,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54932269'] = [
    [
        'document' => 'S94855',
        'header_ref' => 'SH54932269',
        'status' => 'PICK PRTD',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon',
        'ship_to_city' => 'Florence',
        'ship_to_state' => 'NJ',
        'ship_to_ref' => '',
        'qty_ordered' => 150,
        'qty_committed' => 150,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54932271'] = [
    [
        'document' => 'S94856',
        'header_ref' => 'SH54932271',
        'status' => 'PICK PRTD',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon',
        'ship_to_city' => 'Greenwood',
        'ship_to_state' => 'IN',
        'ship_to_ref' => '',
        'qty_ordered' => 100,
        'qty_committed' => 100,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54932312'] = [
    [
        'document' => 'S94857',
        'header_ref' => 'SH54932312',
        'status' => 'PICK PRTD',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Phoenix',
        'ship_to_state' => 'AZ',
        'ship_to_ref' => '',
        'qty_ordered' => 50,
        'qty_committed' => 50,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54937241'] = [
    [
        'document' => 'S94860',
        'header_ref' => 'SH54937241',
        'status' => 'PICK PRTD',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon',
        'ship_to_city' => 'Hazle TWP',
        'ship_to_state' => 'PA',
        'ship_to_ref' => '',
        'qty_ordered' => 50,
        'qty_committed' => 50,
        'warehouse' => 'KENT2',
    ],
    [
        'document' => 'S94904',
        'header_ref' => 'SH54937241',
        'status' => 'PICK PRTD',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon',
        'ship_to_city' => 'Hazle TWP',
        'ship_to_state' => 'PA',
        'ship_to_ref' => '',
        'qty_ordered' => 50,
        'qty_committed' => 50,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54942601'] = [
    [
        'document' => 'S94864',
        'header_ref' => 'SH54942601',
        'status' => 'PICK PRTD',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Phoenix',
        'ship_to_state' => 'AZ',
        'ship_to_ref' => '',
        'qty_ordered' => 100,
        'qty_committed' => 100,
        'warehouse' => 'KENT2',
    ],
    [
        'document' => 'S94917',
        'header_ref' => 'SH54942601',
        'status' => 'PICK PRTD',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Phoenix',
        'ship_to_state' => 'AZ',
        'ship_to_ref' => '',
        'qty_ordered' => 50,
        'qty_committed' => 50,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54942695'] = [
    [
        'document' => 'S94866',
        'header_ref' => 'SH54942695',
        'status' => 'PICK PRTD',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon',
        'ship_to_city' => 'Greenwood',
        'ship_to_state' => 'IN',
        'ship_to_ref' => '',
        'qty_ordered' => 50,
        'qty_committed' => 50,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54947161'] = [
    [
        'document' => 'S94868',
        'header_ref' => 'SH54947161',
        'status' => 'PICK PRTD',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Las Vegas',
        'ship_to_state' => 'NV',
        'ship_to_ref' => '',
        'qty_ordered' => 100,
        'qty_committed' => 100,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54947164'] = [
    [
        'document' => 'S94869',
        'header_ref' => 'SH54947164',
        'status' => 'PICK PRTD',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon',
        'ship_to_city' => 'Huntley',
        'ship_to_state' => 'IL',
        'ship_to_ref' => '',
        'qty_ordered' => 50,
        'qty_committed' => 50,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54947166'] = [
    [
        'document' => 'S94870',
        'header_ref' => 'SH54947166',
        'status' => 'PICK PRTD',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Perrysburg',
        'ship_to_state' => 'OH',
        'ship_to_ref' => '',
        'qty_ordered' => 150,
        'qty_committed' => 150,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54947175'] = [
    [
        'document' => 'S94871',
        'header_ref' => 'SH54947175',
        'status' => 'PICK PRTD',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Phoenix',
        'ship_to_state' => 'AZ',
        'ship_to_ref' => '',
        'qty_ordered' => 50,
        'qty_committed' => 50,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54947282'] = [
    [
        'document' => 'S94873',
        'header_ref' => 'SH54947282',
        'status' => 'PICK PRTD',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon',
        'ship_to_city' => 'Greenwood',
        'ship_to_state' => 'IN',
        'ship_to_ref' => '',
        'qty_ordered' => 100,
        'qty_committed' => 100,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54952193'] = [
    [
        'document' => 'S94874',
        'header_ref' => 'SH54952193',
        'status' => 'PICK PRTD',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Phoenix',
        'ship_to_state' => 'AZ',
        'ship_to_ref' => '',
        'qty_ordered' => 50,
        'qty_committed' => 50,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54952197'] = [
    [
        'document' => 'S94876',
        'header_ref' => 'SH54952197',
        'status' => 'PICK PRTD',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon',
        'ship_to_city' => 'Huntley',
        'ship_to_state' => 'IL',
        'ship_to_ref' => '',
        'qty_ordered' => 100,
        'qty_committed' => 100,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54952225'] = [
    [
        'document' => 'S94877',
        'header_ref' => 'SH54952225',
        'status' => 'PICK PRTD',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon',
        'ship_to_city' => 'Hazle TWP',
        'ship_to_state' => 'PA',
        'ship_to_ref' => '',
        'qty_ordered' => 250,
        'qty_committed' => 250,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54952236'] = [
    [
        'document' => 'S94878',
        'header_ref' => 'SH54952236',
        'status' => 'PICK PRTD',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon',
        'ship_to_city' => 'Greenwood',
        'ship_to_state' => 'IN',
        'ship_to_ref' => '',
        'qty_ordered' => 100,
        'qty_committed' => 100,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54952283'] = [
    [
        'document' => 'S94880',
        'header_ref' => 'SH54952283',
        'status' => 'PICK PRTD',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Las Vegas',
        'ship_to_state' => 'NV',
        'ship_to_ref' => '',
        'qty_ordered' => 50,
        'qty_committed' => 50,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54942690'] = [
    [
        'document' => 'S94918',
        'header_ref' => 'SH54942690',
        'status' => 'PICK PRTD',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Moreno Valley',
        'ship_to_state' => 'CA',
        'ship_to_ref' => '',
        'qty_ordered' => 50,
        'qty_committed' => 50,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54947262'] = [
    [
        'document' => 'S94920',
        'header_ref' => 'SH54947262',
        'status' => 'PICK PRTD',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Las Vegas',
        'ship_to_state' => 'NV',
        'ship_to_ref' => '',
        'qty_ordered' => 50,
        'qty_committed' => 50,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54947419'] = [
    [
        'document' => 'S94922',
        'header_ref' => 'SH54947419',
        'status' => 'PICK PRTD',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon',
        'ship_to_city' => 'Greenwood',
        'ship_to_state' => 'IN',
        'ship_to_ref' => '',
        'qty_ordered' => 50,
        'qty_committed' => 50,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54947420'] = [
    [
        'document' => 'S94923',
        'header_ref' => 'SH54947420',
        'status' => 'PICK PRTD',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Phoenix',
        'ship_to_state' => 'AZ',
        'ship_to_ref' => '',
        'qty_ordered' => 50,
        'qty_committed' => 50,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54952141'] = [
    [
        'document' => 'S94926',
        'header_ref' => 'SH54952141',
        'status' => 'PICK PRTD',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon',
        'ship_to_city' => 'Greenwood',
        'ship_to_state' => 'IN',
        'ship_to_ref' => '',
        'qty_ordered' => 50,
        'qty_committed' => 50,
        'warehouse' => 'KENT2',
    ],
    [
        'document' => 'S94964',
        'header_ref' => 'SH54952141',
        'status' => 'PICK PRTD',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon',
        'ship_to_city' => 'Greenwood',
        'ship_to_state' => 'IN',
        'ship_to_ref' => '',
        'qty_ordered' => 200,
        'qty_committed' => 200,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54952145'] = [
    [
        'document' => 'S94927',
        'header_ref' => 'SH54952145',
        'status' => 'PICK PRTD',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Phoenix',
        'ship_to_state' => 'AZ',
        'ship_to_ref' => '',
        'qty_ordered' => 50,
        'qty_committed' => 50,
        'warehouse' => 'KENT2',
    ],
    [
        'document' => 'S94965',
        'header_ref' => 'SH54952145',
        'status' => 'PICK PRTD',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Phoenix',
        'ship_to_state' => 'AZ',
        'ship_to_ref' => '',
        'qty_ordered' => 200,
        'qty_committed' => 200,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54952148'] = [
    [
        'document' => 'S94928',
        'header_ref' => 'SH54952148',
        'status' => 'PICK PRTD',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon',
        'ship_to_city' => 'Hazle TWP',
        'ship_to_state' => 'PA',
        'ship_to_ref' => '',
        'qty_ordered' => 50,
        'qty_committed' => 50,
        'warehouse' => 'KENT2',
    ],
    [
        'document' => 'S94966',
        'header_ref' => 'SH54952148',
        'status' => 'PICK PRTD',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon',
        'ship_to_city' => 'Hazle TWP',
        'ship_to_state' => 'PA',
        'ship_to_ref' => '',
        'qty_ordered' => 50,
        'qty_committed' => 50,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54952158'] = [
    [
        'document' => 'S94929',
        'header_ref' => 'SH54952158',
        'status' => 'PICK PRTD',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Moreno Valley',
        'ship_to_state' => 'CA',
        'ship_to_ref' => '',
        'qty_ordered' => 50,
        'qty_committed' => 50,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54876634'] = [
    [
        'document' => 'S94930',
        'header_ref' => 'SH54876634',
        'status' => 'PICK PRTD',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Rancho Cordova',
        'ship_to_state' => 'CA',
        'ship_to_ref' => '',
        'qty_ordered' => 50,
        'qty_committed' => 50,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54882151'] = [
    [
        'document' => 'S94931',
        'header_ref' => 'SH54882151',
        'status' => 'PICK PRTD',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Rialto',
        'ship_to_state' => 'CA',
        'ship_to_ref' => '',
        'qty_ordered' => 50,
        'qty_committed' => 50,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54887823'] = [
    [
        'document' => 'S94957',
        'header_ref' => 'SH54887823',
        'status' => 'PICK PRTD',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Bloomington',
        'ship_to_state' => 'CA',
        'ship_to_ref' => '',
        'qty_ordered' => 50,
        'qty_committed' => 50,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54893557'] = [
    [
        'document' => 'S94958',
        'header_ref' => 'SH54893557',
        'status' => 'PICK PRTD',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Liberty',
        'ship_to_state' => 'MO',
        'ship_to_ref' => '',
        'qty_ordered' => 50,
        'qty_committed' => 50,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54899578'] = [
    [
        'document' => 'S94959',
        'header_ref' => 'SH54899578',
        'status' => 'PICK PRTD',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon',
        'ship_to_city' => 'Greenwood',
        'ship_to_state' => 'IN',
        'ship_to_ref' => '',
        'qty_ordered' => 50,
        'qty_committed' => 50,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54937263'] = [
    [
        'document' => 'S94960',
        'header_ref' => 'SH54937263',
        'status' => 'PICK PRTD',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon',
        'ship_to_city' => 'Huntley',
        'ship_to_state' => 'IL',
        'ship_to_ref' => '',
        'qty_ordered' => 1000,
        'qty_committed' => 1000,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54942662'] = [
    [
        'document' => 'S94961',
        'header_ref' => 'SH54942662',
        'status' => 'PICK PRTD',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Las Vegas',
        'ship_to_state' => 'NV',
        'ship_to_ref' => '',
        'qty_ordered' => 500,
        'qty_committed' => 500,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54942707'] = [
    [
        'document' => 'S94962',
        'header_ref' => 'SH54942707',
        'status' => 'PICK PRTD',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon',
        'ship_to_city' => 'Hazle TWP',
        'ship_to_state' => 'PA',
        'ship_to_ref' => '',
        'qty_ordered' => 500,
        'qty_committed' => 500,
        'warehouse' => 'KENT2',
    ],
];

$po_index = [];