<?php
// Auto-generated from: Shipments LEADHANDKENT2 2026-08-31T15_02_46.xlsx on 2026-08-31 15:03:16

$cancelled_sh = ['SH54819933'];

$order_data = [];
$order_data['SH54932454'] = [
    [
        'document' => 'S92793',
        'header_ref' => 'SH54932454',
        'status' => 'SCANCOMP',
        'date_to_ship' => '9/2/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Medline Industries',
        'ship_to_city' => 'Jeffersonville',
        'ship_to_state' => 'IN',
        'ship_to_ref' => '',
        'qty_ordered' => 40,
        'qty_committed' => 40,
        'warehouse' => 'KENT2',
    ],
    [
        'document' => 'S92801',
        'header_ref' => 'SH54932454',
        'status' => 'SCANCOMP',
        'date_to_ship' => '9/2/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Medline Industries',
        'ship_to_city' => 'Jeffersonville',
        'ship_to_state' => 'IN',
        'ship_to_ref' => '',
        'qty_ordered' => 180,
        'qty_committed' => 180,
        'warehouse' => 'KENT2',
    ],
    [
        'document' => 'S92805',
        'header_ref' => 'SH54932454',
        'status' => 'SCANCOMP',
        'date_to_ship' => '9/2/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Medline Industries',
        'ship_to_city' => 'Jeffersonville',
        'ship_to_state' => 'IN',
        'ship_to_ref' => '',
        'qty_ordered' => 19200,
        'qty_committed' => 19200,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54932484'] = [
    [
        'document' => 'S92795',
        'header_ref' => 'SH54932484',
        'status' => 'SCANCOMP',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Medline Industries',
        'ship_to_city' => 'Auburndale',
        'ship_to_state' => 'FL',
        'ship_to_ref' => '',
        'qty_ordered' => 30,
        'qty_committed' => 30,
        'warehouse' => 'KENT2',
    ],
    [
        'document' => 'S92802',
        'header_ref' => 'SH54932484',
        'status' => 'SCANCOMP',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Medline Industries',
        'ship_to_city' => 'Auburndale',
        'ship_to_state' => 'FL',
        'ship_to_ref' => '',
        'qty_ordered' => 100,
        'qty_committed' => 100,
        'warehouse' => 'KENT2',
    ],
    [
        'document' => 'S92806',
        'header_ref' => 'SH54932484',
        'status' => 'SCANCOMP',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Medline Industries',
        'ship_to_city' => 'Auburndale',
        'ship_to_state' => 'FL',
        'ship_to_ref' => '',
        'qty_ordered' => 60800,
        'qty_committed' => 60800,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54876501'] = [
    [
        'document' => 'S92836',
        'header_ref' => 'SH54876501',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Easton',
        'ship_to_state' => 'PA',
        'ship_to_ref' => '',
        'qty_ordered' => 163,
        'qty_committed' => 163,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54882109'] = [
    [
        'document' => 'S92837',
        'header_ref' => 'SH54882109',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Kansas City',
        'ship_to_state' => 'KS',
        'ship_to_ref' => '',
        'qty_ordered' => 2,
        'qty_committed' => 2,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54882124'] = [
    [
        'document' => 'S92839',
        'header_ref' => 'SH54882124',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Monroe',
        'ship_to_state' => 'OH',
        'ship_to_ref' => '',
        'qty_ordered' => 6,
        'qty_committed' => 6,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54899559'] = [
    [
        'document' => 'S92840',
        'header_ref' => 'SH54899559',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Lebanon',
        'ship_to_state' => 'TN',
        'ship_to_ref' => '',
        'qty_ordered' => 24,
        'qty_committed' => 24,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54899560'] = [
    [
        'document' => 'S92841',
        'header_ref' => 'SH54899560',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Charleston',
        'ship_to_state' => 'TN',
        'ship_to_ref' => '',
        'qty_ordered' => 54,
        'qty_committed' => 54,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54899580'] = [
    [
        'document' => 'S92842',
        'header_ref' => 'SH54899580',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Oklahoma City',
        'ship_to_state' => 'OK',
        'ship_to_ref' => '',
        'qty_ordered' => 23,
        'qty_committed' => 23,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54899585'] = [
    [
        'document' => 'S92843',
        'header_ref' => 'SH54899585',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon',
        'ship_to_city' => 'Fort Wayne',
        'ship_to_state' => 'IN',
        'ship_to_ref' => '',
        'qty_ordered' => 18,
        'qty_committed' => 18,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54899586'] = [
    [
        'document' => 'S92844',
        'header_ref' => 'SH54899586',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Schertz',
        'ship_to_state' => 'TX',
        'ship_to_ref' => '',
        'qty_ordered' => 19,
        'qty_committed' => 19,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54899595'] = [
    [
        'document' => 'S92845',
        'header_ref' => 'SH54899595',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Carncro',
        'ship_to_state' => 'LA',
        'ship_to_ref' => '',
        'qty_ordered' => 6,
        'qty_committed' => 6,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54899598'] = [
    [
        'document' => 'S92846',
        'header_ref' => 'SH54899598',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'York',
        'ship_to_state' => 'PA',
        'ship_to_ref' => '',
        'qty_ordered' => 27,
        'qty_committed' => 27,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54899602'] = [
    [
        'document' => 'S92847',
        'header_ref' => 'SH54899602',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'North Little Rock',
        'ship_to_state' => 'AR',
        'ship_to_ref' => '',
        'qty_ordered' => 19,
        'qty_committed' => 19,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54899603'] = [
    [
        'document' => 'S92848',
        'header_ref' => 'SH54899603',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Sparrows Point',
        'ship_to_state' => 'MD',
        'ship_to_ref' => '',
        'qty_ordered' => 14,
        'qty_committed' => 14,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54899604'] = [
    [
        'document' => 'S92849',
        'header_ref' => 'SH54899604',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon',
        'ship_to_city' => 'Fredericksburg',
        'ship_to_state' => 'VA',
        'ship_to_ref' => '',
        'qty_ordered' => 11,
        'qty_committed' => 11,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54899605'] = [
    [
        'document' => 'S92850',
        'header_ref' => 'SH54899605',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'New Castle',
        'ship_to_state' => 'DE',
        'ship_to_ref' => '',
        'qty_ordered' => 23,
        'qty_committed' => 23,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54899681'] = [
    [
        'document' => 'S92851',
        'header_ref' => 'SH54899681',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'West Jordan',
        'ship_to_state' => 'UT',
        'ship_to_ref' => '',
        'qty_ordered' => 50,
        'qty_committed' => 50,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54899682'] = [
    [
        'document' => 'S92852',
        'header_ref' => 'SH54899682',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Edwardsville',
        'ship_to_state' => 'IL',
        'ship_to_ref' => '',
        'qty_ordered' => 25,
        'qty_committed' => 25,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54899684'] = [
    [
        'document' => 'S92853',
        'header_ref' => 'SH54899684',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Groveport',
        'ship_to_state' => 'OH',
        'ship_to_ref' => '',
        'qty_ordered' => 36,
        'qty_committed' => 36,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54899685'] = [
    [
        'document' => 'S92854',
        'header_ref' => 'SH54899685',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Phoenix',
        'ship_to_state' => 'AZ',
        'ship_to_ref' => '',
        'qty_ordered' => 15,
        'qty_committed' => 15,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54899687'] = [
    [
        'document' => 'S92855',
        'header_ref' => 'SH54899687',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Dupont',
        'ship_to_state' => 'WA',
        'ship_to_ref' => '',
        'qty_ordered' => 26,
        'qty_committed' => 26,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54899688'] = [
    [
        'document' => 'S92856',
        'header_ref' => 'SH54899688',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Auburndale',
        'ship_to_state' => 'FL',
        'ship_to_ref' => '',
        'qty_ordered' => 38,
        'qty_committed' => 38,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54899689'] = [
    [
        'document' => 'S93149',
        'header_ref' => 'SH54899689',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Patterson',
        'ship_to_state' => 'CA',
        'ship_to_ref' => '',
        'qty_ordered' => 25,
        'qty_committed' => 25,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54899690'] = [
    [
        'document' => 'S93150',
        'header_ref' => 'SH54899690',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Canton',
        'ship_to_state' => 'OH',
        'ship_to_ref' => '',
        'qty_ordered' => 61,
        'qty_committed' => 61,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54899691'] = [
    [
        'document' => 'S93151',
        'header_ref' => 'SH54899691',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Easton',
        'ship_to_state' => 'PA',
        'ship_to_ref' => '',
        'qty_ordered' => 20,
        'qty_committed' => 20,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54899696'] = [
    [
        'document' => 'S93152',
        'header_ref' => 'SH54899696',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'University Park',
        'ship_to_state' => 'IL',
        'ship_to_ref' => '',
        'qty_ordered' => 17,
        'qty_committed' => 17,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54899697'] = [
    [
        'document' => 'S93153',
        'header_ref' => 'SH54899697',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Burlington',
        'ship_to_state' => 'NJ',
        'ship_to_ref' => '',
        'qty_ordered' => 64,
        'qty_committed' => 64,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54899698'] = [
    [
        'document' => 'S93154',
        'header_ref' => 'SH54899698',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Imperial',
        'ship_to_state' => 'PA',
        'ship_to_ref' => '',
        'qty_ordered' => 16,
        'qty_committed' => 16,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54899699'] = [
    [
        'document' => 'S93156',
        'header_ref' => 'SH54899699',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Turlock',
        'ship_to_state' => 'CA',
        'ship_to_ref' => '',
        'qty_ordered' => 42,
        'qty_committed' => 42,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54899700'] = [
    [
        'document' => 'S93157',
        'header_ref' => 'SH54899700',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Lakeland',
        'ship_to_state' => 'FL',
        'ship_to_ref' => '',
        'qty_ordered' => 21,
        'qty_committed' => 21,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54899701'] = [
    [
        'document' => 'S93158',
        'header_ref' => 'SH54899701',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Republic',
        'ship_to_state' => 'MO',
        'ship_to_ref' => '',
        'qty_ordered' => 32,
        'qty_committed' => 32,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54905235'] = [
    [
        'document' => 'S93159',
        'header_ref' => 'SH54905235',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Charleston',
        'ship_to_state' => 'TN',
        'ship_to_ref' => '',
        'qty_ordered' => 2,
        'qty_committed' => 2,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54905270'] = [
    [
        'document' => 'S93160',
        'header_ref' => 'SH54905270',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Coppell',
        'ship_to_state' => 'TX',
        'ship_to_ref' => '',
        'qty_ordered' => 3,
        'qty_committed' => 3,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54905300'] = [
    [
        'document' => 'S93161',
        'header_ref' => 'SH54905300',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Schertz',
        'ship_to_state' => 'TX',
        'ship_to_ref' => '',
        'qty_ordered' => 1,
        'qty_committed' => 1,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54905305'] = [
    [
        'document' => 'S93162',
        'header_ref' => 'SH54905305',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Kansas City',
        'ship_to_state' => 'KS',
        'ship_to_ref' => '',
        'qty_ordered' => 44,
        'qty_committed' => 44,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54905307'] = [
    [
        'document' => 'S93163',
        'header_ref' => 'SH54905307',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Channahon',
        'ship_to_state' => 'IL',
        'ship_to_ref' => '',
        'qty_ordered' => 8,
        'qty_committed' => 8,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54905311'] = [
    [
        'document' => 'S93164',
        'header_ref' => 'SH54905311',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Concord',
        'ship_to_state' => 'NC',
        'ship_to_ref' => '',
        'qty_ordered' => 1,
        'qty_committed' => 1,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54905366'] = [
    [
        'document' => 'S93165',
        'header_ref' => 'SH54905366',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Canton',
        'ship_to_state' => 'OH',
        'ship_to_ref' => '',
        'qty_ordered' => 2,
        'qty_committed' => 2,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54905367'] = [
    [
        'document' => 'S93167',
        'header_ref' => 'SH54905367',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'New Castle',
        'ship_to_state' => 'DE',
        'ship_to_ref' => '',
        'qty_ordered' => 1,
        'qty_committed' => 1,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54905372'] = [
    [
        'document' => 'S93168',
        'header_ref' => 'SH54905372',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Sparrows Point',
        'ship_to_state' => 'MD',
        'ship_to_ref' => '',
        'qty_ordered' => 8,
        'qty_committed' => 8,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54905374'] = [
    [
        'document' => 'S93169',
        'header_ref' => 'SH54905374',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Fall River',
        'ship_to_state' => 'MA',
        'ship_to_ref' => '',
        'qty_ordered' => 6,
        'qty_committed' => 6,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54905375'] = [
    [
        'document' => 'S93170',
        'header_ref' => 'SH54905375',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Spokane',
        'ship_to_state' => 'WA',
        'ship_to_ref' => '',
        'qty_ordered' => 7,
        'qty_committed' => 7,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54905376'] = [
    [
        'document' => 'S93171',
        'header_ref' => 'SH54905376',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Patterson',
        'ship_to_state' => 'CA',
        'ship_to_ref' => '',
        'qty_ordered' => 26,
        'qty_committed' => 26,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54905377'] = [
    [
        'document' => 'S93172',
        'header_ref' => 'SH54905377',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Livonia',
        'ship_to_state' => 'MI',
        'ship_to_ref' => '',
        'qty_ordered' => 7,
        'qty_committed' => 7,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54905378'] = [
    [
        'document' => 'S93173',
        'header_ref' => 'SH54905378',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Lakeland',
        'ship_to_state' => 'FL',
        'ship_to_ref' => '',
        'qty_ordered' => 1,
        'qty_committed' => 1,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54905379'] = [
    [
        'document' => 'S93174',
        'header_ref' => 'SH54905379',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Groveport',
        'ship_to_state' => 'OH',
        'ship_to_ref' => '',
        'qty_ordered' => 2,
        'qty_committed' => 2,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54905380'] = [
    [
        'document' => 'S93175',
        'header_ref' => 'SH54905380',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Las Vegas',
        'ship_to_state' => 'NV',
        'ship_to_ref' => '',
        'qty_ordered' => 10,
        'qty_committed' => 10,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54905381'] = [
    [
        'document' => 'S93176',
        'header_ref' => 'SH54905381',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Castleton-On-Hudson',
        'ship_to_state' => 'NY',
        'ship_to_ref' => '',
        'qty_ordered' => 3,
        'qty_committed' => 3,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54910725'] = [
    [
        'document' => 'S93177',
        'header_ref' => 'SH54910725',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Clear Brook',
        'ship_to_state' => 'VA',
        'ship_to_ref' => '',
        'qty_ordered' => 12,
        'qty_committed' => 12,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54910744'] = [
    [
        'document' => 'S93178',
        'header_ref' => 'SH54910744',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Fresno',
        'ship_to_state' => 'TX',
        'ship_to_ref' => '',
        'qty_ordered' => 1,
        'qty_committed' => 1,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54910748'] = [
    [
        'document' => 'S93179',
        'header_ref' => 'SH54910748',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Schertz',
        'ship_to_state' => 'TX',
        'ship_to_ref' => '',
        'qty_ordered' => 1,
        'qty_committed' => 1,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54910751'] = [
    [
        'document' => 'S93180',
        'header_ref' => 'SH54910751',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'West Jordan',
        'ship_to_state' => 'UT',
        'ship_to_ref' => '',
        'qty_ordered' => 4,
        'qty_committed' => 4,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54910755'] = [
    [
        'document' => 'S93181',
        'header_ref' => 'SH54910755',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Aurora',
        'ship_to_state' => 'CO',
        'ship_to_ref' => '',
        'qty_ordered' => 3,
        'qty_committed' => 3,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54910756'] = [
    [
        'document' => 'S93182',
        'header_ref' => 'SH54910756',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Cinnaminson Twp',
        'ship_to_state' => 'NJ',
        'ship_to_ref' => '',
        'qty_ordered' => 3,
        'qty_committed' => 3,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54910757'] = [
    [
        'document' => 'S93183',
        'header_ref' => 'SH54910757',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Kernersville',
        'ship_to_state' => 'NC',
        'ship_to_ref' => '',
        'qty_ordered' => 22,
        'qty_committed' => 22,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54910759'] = [
    [
        'document' => 'S93184',
        'header_ref' => 'SH54910759',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Charleston',
        'ship_to_state' => 'TN',
        'ship_to_ref' => '',
        'qty_ordered' => 2,
        'qty_committed' => 2,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54910804'] = [
    [
        'document' => 'S93186',
        'header_ref' => 'SH54910804',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Livonia',
        'ship_to_state' => 'MI',
        'ship_to_ref' => '',
        'qty_ordered' => 3,
        'qty_committed' => 3,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54910807'] = [
    [
        'document' => 'S93187',
        'header_ref' => 'SH54910807',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Monroe',
        'ship_to_state' => 'OH',
        'ship_to_ref' => '',
        'qty_ordered' => 4,
        'qty_committed' => 4,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54910808'] = [
    [
        'document' => 'S93188',
        'header_ref' => 'SH54910808',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Monroe',
        'ship_to_state' => 'OH',
        'ship_to_ref' => '',
        'qty_ordered' => 5,
        'qty_committed' => 5,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54910811'] = [
    [
        'document' => 'S93189',
        'header_ref' => 'SH54910811',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'March Air Reserve Base',
        'ship_to_state' => 'CA',
        'ship_to_ref' => '',
        'qty_ordered' => 14,
        'qty_committed' => 14,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54910812'] = [
    [
        'document' => 'S93190',
        'header_ref' => 'SH54910812',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Canton',
        'ship_to_state' => 'OH',
        'ship_to_ref' => '',
        'qty_ordered' => 2,
        'qty_committed' => 2,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54910813'] = [
    [
        'document' => 'S93191',
        'header_ref' => 'SH54910813',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Apopka',
        'ship_to_state' => 'FL',
        'ship_to_ref' => '',
        'qty_ordered' => 1,
        'qty_committed' => 1,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54910814'] = [
    [
        'document' => 'S93192',
        'header_ref' => 'SH54910814',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Stockton',
        'ship_to_state' => 'CA',
        'ship_to_ref' => '',
        'qty_ordered' => 17,
        'qty_committed' => 17,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54916294'] = [
    [
        'document' => 'S93193',
        'header_ref' => 'SH54916294',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Goodyear',
        'ship_to_state' => 'AZ',
        'ship_to_ref' => '',
        'qty_ordered' => 21,
        'qty_committed' => 21,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54916300'] = [
    [
        'document' => 'S93194',
        'header_ref' => 'SH54916300',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'West Jordan',
        'ship_to_state' => 'UT',
        'ship_to_ref' => '',
        'qty_ordered' => 9,
        'qty_committed' => 9,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54916302'] = [
    [
        'document' => 'S93195',
        'header_ref' => 'SH54916302',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Coppell',
        'ship_to_state' => 'TX',
        'ship_to_ref' => '',
        'qty_ordered' => 46,
        'qty_committed' => 46,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54916308'] = [
    [
        'document' => 'S93197',
        'header_ref' => 'SH54916308',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Rock Tavern',
        'ship_to_state' => 'NY',
        'ship_to_ref' => '',
        'qty_ordered' => 9,
        'qty_committed' => 9,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54916309'] = [
    [
        'document' => 'S93198',
        'header_ref' => 'SH54916309',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Clear Brook',
        'ship_to_state' => 'VA',
        'ship_to_ref' => '',
        'qty_ordered' => 10,
        'qty_committed' => 10,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54916314'] = [
    [
        'document' => 'S93199',
        'header_ref' => 'SH54916314',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Cinnaminson Twp',
        'ship_to_state' => 'NJ',
        'ship_to_ref' => '',
        'qty_ordered' => 26,
        'qty_committed' => 26,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54916430'] = [
    [
        'document' => 'S93200',
        'header_ref' => 'SH54916430',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'San Bernadino',
        'ship_to_state' => 'CA',
        'ship_to_ref' => '',
        'qty_ordered' => 1,
        'qty_committed' => 1,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54916432'] = [
    [
        'document' => 'S93201',
        'header_ref' => 'SH54916432',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Charleston',
        'ship_to_state' => 'TN',
        'ship_to_ref' => '',
        'qty_ordered' => 12,
        'qty_committed' => 12,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54916433'] = [
    [
        'document' => 'S93202',
        'header_ref' => 'SH54916433',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Channahon',
        'ship_to_state' => 'IL',
        'ship_to_ref' => '',
        'qty_ordered' => 14,
        'qty_committed' => 14,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54916435'] = [
    [
        'document' => 'S93203',
        'header_ref' => 'SH54916435',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Republic',
        'ship_to_state' => 'MO',
        'ship_to_ref' => '',
        'qty_ordered' => 7,
        'qty_committed' => 7,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54916436'] = [
    [
        'document' => 'S93204',
        'header_ref' => 'SH54916436',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Turlock',
        'ship_to_state' => 'CA',
        'ship_to_ref' => '',
        'qty_ordered' => 7,
        'qty_committed' => 7,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54916437'] = [
    [
        'document' => 'S93205',
        'header_ref' => 'SH54916437',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Dupont',
        'ship_to_state' => 'WA',
        'ship_to_ref' => '',
        'qty_ordered' => 15,
        'qty_committed' => 15,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54916438'] = [
    [
        'document' => 'S93206',
        'header_ref' => 'SH54916438',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Lakeland',
        'ship_to_state' => 'FL',
        'ship_to_ref' => '',
        'qty_ordered' => 8,
        'qty_committed' => 8,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54916439'] = [
    [
        'document' => 'S93207',
        'header_ref' => 'SH54916439',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Groveport',
        'ship_to_state' => 'OH',
        'ship_to_ref' => '',
        'qty_ordered' => 62,
        'qty_committed' => 62,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54916442'] = [
    [
        'document' => 'S93209',
        'header_ref' => 'SH54916442',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'York',
        'ship_to_state' => 'PA',
        'ship_to_ref' => '',
        'qty_ordered' => 22,
        'qty_committed' => 22,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54916443'] = [
    [
        'document' => 'S93210',
        'header_ref' => 'SH54916443',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'New Castle',
        'ship_to_state' => 'DE',
        'ship_to_ref' => '',
        'qty_ordered' => 7,
        'qty_committed' => 7,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54916444'] = [
    [
        'document' => 'S93211',
        'header_ref' => 'SH54916444',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Visalia',
        'ship_to_state' => 'CA',
        'ship_to_ref' => '',
        'qty_ordered' => 35,
        'qty_committed' => 35,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54916446'] = [
    [
        'document' => 'S93212',
        'header_ref' => 'SH54916446',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Apopka',
        'ship_to_state' => 'FL',
        'ship_to_ref' => '',
        'qty_ordered' => 14,
        'qty_committed' => 14,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54916448'] = [
    [
        'document' => 'S93213',
        'header_ref' => 'SH54916448',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Concord',
        'ship_to_state' => 'NC',
        'ship_to_ref' => '',
        'qty_ordered' => 23,
        'qty_committed' => 23,
        'warehouse' => 'KENT2',
    ],
];
$order_data['EMHU269476'] = [
    [
        'document' => 'S93231',
        'header_ref' => 'EMHU269476',
        'status' => 'BOL PRTD',
        'date_to_ship' => '8/31/2026',
        'carrier_code' => 'LOGIC',
        'ship_to_name' => 'HEALTH SMART',
        'ship_to_city' => 'WAUKEGAN',
        'ship_to_state' => 'IL',
        'ship_to_ref' => '',
        'qty_ordered' => 5340,
        'qty_committed' => 3264,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54916450'] = [
    [
        'document' => 'S93239',
        'header_ref' => 'SH54916450',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Park City',
        'ship_to_state' => 'KS',
        'ship_to_ref' => '',
        'qty_ordered' => 3,
        'qty_committed' => 3,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54916451'] = [
    [
        'document' => 'S93240',
        'header_ref' => 'SH54916451',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Auburndale',
        'ship_to_state' => 'FL',
        'ship_to_ref' => '',
        'qty_ordered' => 18,
        'qty_committed' => 18,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54916452'] = [
    [
        'document' => 'S93241',
        'header_ref' => 'SH54916452',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Lebanon',
        'ship_to_state' => 'TN',
        'ship_to_ref' => '',
        'qty_ordered' => 10,
        'qty_committed' => 10,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54921974'] = [
    [
        'document' => 'S93242',
        'header_ref' => 'SH54921974',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Kernersville',
        'ship_to_state' => 'NC',
        'ship_to_ref' => '',
        'qty_ordered' => 1,
        'qty_committed' => 1,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54921975'] = [
    [
        'document' => 'S93243',
        'header_ref' => 'SH54921975',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Phoenix',
        'ship_to_state' => 'AZ',
        'ship_to_ref' => '',
        'qty_ordered' => 4,
        'qty_committed' => 4,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54921977'] = [
    [
        'document' => 'S93245',
        'header_ref' => 'SH54921977',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Lakeland',
        'ship_to_state' => 'FL',
        'ship_to_ref' => '',
        'qty_ordered' => 1,
        'qty_committed' => 1,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54921979'] = [
    [
        'document' => 'S93255',
        'header_ref' => 'SH54921979',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Lebanon',
        'ship_to_state' => 'TN',
        'ship_to_ref' => '',
        'qty_ordered' => 4,
        'qty_committed' => 4,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54921986'] = [
    [
        'document' => 'S93257',
        'header_ref' => 'SH54921986',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'North Little Rock',
        'ship_to_state' => 'AR',
        'ship_to_ref' => '',
        'qty_ordered' => 5,
        'qty_committed' => 5,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54921988'] = [
    [
        'document' => 'S93258',
        'header_ref' => 'SH54921988',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Redlands',
        'ship_to_state' => 'CA',
        'ship_to_ref' => '',
        'qty_ordered' => 27,
        'qty_committed' => 27,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54921989'] = [
    [
        'document' => 'S93259',
        'header_ref' => 'SH54921989',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'West Jordan',
        'ship_to_state' => 'UT',
        'ship_to_ref' => '',
        'qty_ordered' => 3,
        'qty_committed' => 3,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54921992'] = [
    [
        'document' => 'S93260',
        'header_ref' => 'SH54921992',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Schertz',
        'ship_to_state' => 'TX',
        'ship_to_ref' => '',
        'qty_ordered' => 11,
        'qty_committed' => 11,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54922008'] = [
    [
        'document' => 'S93261',
        'header_ref' => 'SH54922008',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Dupont',
        'ship_to_state' => 'WA',
        'ship_to_ref' => '',
        'qty_ordered' => 33,
        'qty_committed' => 33,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54922042'] = [
    [
        'document' => 'S93262',
        'header_ref' => 'SH54922042',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon',
        'ship_to_city' => 'Fort Wayne',
        'ship_to_state' => 'IN',
        'ship_to_ref' => '',
        'qty_ordered' => 5,
        'qty_committed' => 5,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54922043'] = [
    [
        'document' => 'S93263',
        'header_ref' => 'SH54922043',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Canton',
        'ship_to_state' => 'OH',
        'ship_to_ref' => '',
        'qty_ordered' => 20,
        'qty_committed' => 20,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54922044'] = [
    [
        'document' => 'S93264',
        'header_ref' => 'SH54922044',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'March Air Reserve Base',
        'ship_to_state' => 'CA',
        'ship_to_ref' => '',
        'qty_ordered' => 1,
        'qty_committed' => 1,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54922045'] = [
    [
        'document' => 'S93265',
        'header_ref' => 'SH54922045',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Cranbury',
        'ship_to_state' => 'NJ',
        'ship_to_ref' => '',
        'qty_ordered' => 15,
        'qty_committed' => 15,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54922048'] = [
    [
        'document' => 'S93266',
        'header_ref' => 'SH54922048',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Fisherville',
        'ship_to_state' => 'VA',
        'ship_to_ref' => '',
        'qty_ordered' => 8,
        'qty_committed' => 8,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54922049'] = [
    [
        'document' => 'S93267',
        'header_ref' => 'SH54922049',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Easton',
        'ship_to_state' => 'PA',
        'ship_to_ref' => '',
        'qty_ordered' => 4,
        'qty_committed' => 4,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54922050'] = [
    [
        'document' => 'S93268',
        'header_ref' => 'SH54922050',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Imperial',
        'ship_to_state' => 'PA',
        'ship_to_ref' => '',
        'qty_ordered' => 6,
        'qty_committed' => 6,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54922051'] = [
    [
        'document' => 'S93269',
        'header_ref' => 'SH54922051',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Oklahoma City',
        'ship_to_state' => 'OK',
        'ship_to_ref' => '',
        'qty_ordered' => 12,
        'qty_committed' => 12,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54922052'] = [
    [
        'document' => 'S93270',
        'header_ref' => 'SH54922052',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'University Park',
        'ship_to_state' => 'IL',
        'ship_to_ref' => '',
        'qty_ordered' => 13,
        'qty_committed' => 13,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54922055'] = [
    [
        'document' => 'S93271',
        'header_ref' => 'SH54922055',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Romeoville',
        'ship_to_state' => 'IL',
        'ship_to_ref' => '',
        'qty_ordered' => 1,
        'qty_committed' => 1,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54922057'] = [
    [
        'document' => 'S93272',
        'header_ref' => 'SH54922057',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'York',
        'ship_to_state' => 'PA',
        'ship_to_ref' => '',
        'qty_ordered' => 1,
        'qty_committed' => 1,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54922058'] = [
    [
        'document' => 'S93273',
        'header_ref' => 'SH54922058',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Penns Grove',
        'ship_to_state' => 'NJ',
        'ship_to_ref' => '',
        'qty_ordered' => 1,
        'qty_committed' => 1,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54922059'] = [
    [
        'document' => 'S93274',
        'header_ref' => 'SH54922059',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'New Castle',
        'ship_to_state' => 'DE',
        'ship_to_ref' => '',
        'qty_ordered' => 2,
        'qty_committed' => 2,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54927199'] = [
    [
        'document' => 'S93275',
        'header_ref' => 'SH54927199',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Republic',
        'ship_to_state' => 'MO',
        'ship_to_ref' => '',
        'qty_ordered' => 2,
        'qty_committed' => 2,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54927206'] = [
    [
        'document' => 'S93276',
        'header_ref' => 'SH54927206',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Redlands',
        'ship_to_state' => 'CA',
        'ship_to_ref' => '',
        'qty_ordered' => 10,
        'qty_committed' => 10,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54927208'] = [
    [
        'document' => 'S93278',
        'header_ref' => 'SH54927208',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'North Little Rock',
        'ship_to_state' => 'AR',
        'ship_to_ref' => '',
        'qty_ordered' => 3,
        'qty_committed' => 3,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54927210'] = [
    [
        'document' => 'S93279',
        'header_ref' => 'SH54927210',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Schertz',
        'ship_to_state' => 'TX',
        'ship_to_ref' => '',
        'qty_ordered' => 8,
        'qty_committed' => 8,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54927212'] = [
    [
        'document' => 'S93280',
        'header_ref' => 'SH54927212',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Goodyear',
        'ship_to_state' => 'AZ',
        'ship_to_ref' => '',
        'qty_ordered' => 5,
        'qty_committed' => 5,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54927213'] = [
    [
        'document' => 'S93282',
        'header_ref' => 'SH54927213',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Monroe',
        'ship_to_state' => 'OH',
        'ship_to_ref' => '',
        'qty_ordered' => 6,
        'qty_committed' => 6,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54927214'] = [
    [
        'document' => 'S93283',
        'header_ref' => 'SH54927214',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Carncro',
        'ship_to_state' => 'LA',
        'ship_to_ref' => '',
        'qty_ordered' => 1,
        'qty_committed' => 1,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54927217'] = [
    [
        'document' => 'S93284',
        'header_ref' => 'SH54927217',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Edwardsville',
        'ship_to_state' => 'IL',
        'ship_to_ref' => '',
        'qty_ordered' => 1,
        'qty_committed' => 1,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54927218'] = [
    [
        'document' => 'S93286',
        'header_ref' => 'SH54927218',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'University Park',
        'ship_to_state' => 'IL',
        'ship_to_ref' => '',
        'qty_ordered' => 1,
        'qty_committed' => 1,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54927219'] = [
    [
        'document' => 'S93287',
        'header_ref' => 'SH54927219',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Kernersville',
        'ship_to_state' => 'NC',
        'ship_to_ref' => '',
        'qty_ordered' => 2,
        'qty_committed' => 2,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54927221'] = [
    [
        'document' => 'S93288',
        'header_ref' => 'SH54927221',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Easton',
        'ship_to_state' => 'PA',
        'ship_to_ref' => '',
        'qty_ordered' => 1,
        'qty_committed' => 1,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54927222'] = [
    [
        'document' => 'S93290',
        'header_ref' => 'SH54927222',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Patterson',
        'ship_to_state' => 'CA',
        'ship_to_ref' => '',
        'qty_ordered' => 20,
        'qty_committed' => 20,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54927223'] = [
    [
        'document' => 'S93291',
        'header_ref' => 'SH54927223',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Cinnaminson Twp',
        'ship_to_state' => 'NJ',
        'ship_to_ref' => '',
        'qty_ordered' => 1,
        'qty_committed' => 1,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54927224'] = [
    [
        'document' => 'S93292',
        'header_ref' => 'SH54927224',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Dupont',
        'ship_to_state' => 'WA',
        'ship_to_ref' => '',
        'qty_ordered' => 2,
        'qty_committed' => 2,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54927225'] = [
    [
        'document' => 'S93294',
        'header_ref' => 'SH54927225',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Fall River',
        'ship_to_state' => 'MA',
        'ship_to_ref' => '',
        'qty_ordered' => 8,
        'qty_committed' => 8,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54927231'] = [
    [
        'document' => 'S93295',
        'header_ref' => 'SH54927231',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Imperial',
        'ship_to_state' => 'PA',
        'ship_to_ref' => '',
        'qty_ordered' => 4,
        'qty_committed' => 4,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54927232'] = [
    [
        'document' => 'S93296',
        'header_ref' => 'SH54927232',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Kansas City',
        'ship_to_state' => 'KS',
        'ship_to_ref' => '',
        'qty_ordered' => 1,
        'qty_committed' => 1,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54927236'] = [
    [
        'document' => 'S93298',
        'header_ref' => 'SH54927236',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Deltona',
        'ship_to_state' => 'FL',
        'ship_to_ref' => '',
        'qty_ordered' => 2,
        'qty_committed' => 2,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54927240'] = [
    [
        'document' => 'S93299',
        'header_ref' => 'SH54927240',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Coppell',
        'ship_to_state' => 'TX',
        'ship_to_ref' => '',
        'qty_ordered' => 7,
        'qty_committed' => 7,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54927242'] = [
    [
        'document' => 'S93300',
        'header_ref' => 'SH54927242',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'York',
        'ship_to_state' => 'PA',
        'ship_to_ref' => '',
        'qty_ordered' => 1,
        'qty_committed' => 1,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54927245'] = [
    [
        'document' => 'S93301',
        'header_ref' => 'SH54927245',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Auburndale',
        'ship_to_state' => 'FL',
        'ship_to_ref' => '',
        'qty_ordered' => 1,
        'qty_committed' => 1,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54932184'] = [
    [
        'document' => 'S93302',
        'header_ref' => 'SH54932184',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Fresno',
        'ship_to_state' => 'TX',
        'ship_to_ref' => '',
        'qty_ordered' => 7,
        'qty_committed' => 7,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54932185'] = [
    [
        'document' => 'S93304',
        'header_ref' => 'SH54932185',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Turlock',
        'ship_to_state' => 'CA',
        'ship_to_ref' => '',
        'qty_ordered' => 10,
        'qty_committed' => 10,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54932187'] = [
    [
        'document' => 'S93305',
        'header_ref' => 'SH54932187',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Edwardsville',
        'ship_to_state' => 'IL',
        'ship_to_ref' => '',
        'qty_ordered' => 4,
        'qty_committed' => 4,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54932188'] = [
    [
        'document' => 'S93306',
        'header_ref' => 'SH54932188',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Kernersville',
        'ship_to_state' => 'NC',
        'ship_to_ref' => '',
        'qty_ordered' => 18,
        'qty_committed' => 18,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54932190'] = [
    [
        'document' => 'S93307',
        'header_ref' => 'SH54932190',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Schertz',
        'ship_to_state' => 'TX',
        'ship_to_ref' => '',
        'qty_ordered' => 1,
        'qty_committed' => 1,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54932191'] = [
    [
        'document' => 'S93308',
        'header_ref' => 'SH54932191',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Schertz',
        'ship_to_state' => 'TX',
        'ship_to_ref' => '',
        'qty_ordered' => 37,
        'qty_committed' => 37,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54932194'] = [
    [
        'document' => 'S93309',
        'header_ref' => 'SH54932194',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Canton',
        'ship_to_state' => 'OH',
        'ship_to_ref' => '',
        'qty_ordered' => 14,
        'qty_committed' => 14,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54932195'] = [
    [
        'document' => 'S93310',
        'header_ref' => 'SH54932195',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Republic',
        'ship_to_state' => 'MO',
        'ship_to_ref' => '',
        'qty_ordered' => 17,
        'qty_committed' => 17,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54932198'] = [
    [
        'document' => 'S93311',
        'header_ref' => 'SH54932198',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Charleston',
        'ship_to_state' => 'TN',
        'ship_to_ref' => '',
        'qty_ordered' => 10,
        'qty_committed' => 10,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54932201'] = [
    [
        'document' => 'S93312',
        'header_ref' => 'SH54932201',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'March Air Reserve Base',
        'ship_to_state' => 'CA',
        'ship_to_ref' => '',
        'qty_ordered' => 9,
        'qty_committed' => 9,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54932203'] = [
    [
        'document' => 'S93316',
        'header_ref' => 'SH54932203',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Coppell',
        'ship_to_state' => 'TX',
        'ship_to_ref' => '',
        'qty_ordered' => 12,
        'qty_committed' => 12,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54932207'] = [
    [
        'document' => 'S93317',
        'header_ref' => 'SH54932207',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Romeoville',
        'ship_to_state' => 'IL',
        'ship_to_ref' => '',
        'qty_ordered' => 12,
        'qty_committed' => 12,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54932208'] = [
    [
        'document' => 'S93318',
        'header_ref' => 'SH54932208',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Visalia',
        'ship_to_state' => 'CA',
        'ship_to_ref' => '',
        'qty_ordered' => 20,
        'qty_committed' => 20,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54932211'] = [
    [
        'document' => 'S93319',
        'header_ref' => 'SH54932211',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Penns Grove',
        'ship_to_state' => 'NJ',
        'ship_to_ref' => '',
        'qty_ordered' => 24,
        'qty_committed' => 24,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54932212'] = [
    [
        'document' => 'S93320',
        'header_ref' => 'SH54932212',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Edgerton',
        'ship_to_state' => 'KS',
        'ship_to_ref' => '',
        'qty_ordered' => 8,
        'qty_committed' => 8,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54932213'] = [
    [
        'document' => 'S93321',
        'header_ref' => 'SH54932213',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Las Vegas',
        'ship_to_state' => 'NV',
        'ship_to_ref' => '',
        'qty_ordered' => 10,
        'qty_committed' => 10,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54932214'] = [
    [
        'document' => 'S93322',
        'header_ref' => 'SH54932214',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Lebanon',
        'ship_to_state' => 'TN',
        'ship_to_ref' => '',
        'qty_ordered' => 7,
        'qty_committed' => 7,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54932291'] = [
    [
        'document' => 'S93323',
        'header_ref' => 'SH54932291',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Fall River',
        'ship_to_state' => 'MA',
        'ship_to_ref' => '',
        'qty_ordered' => 6,
        'qty_committed' => 6,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54932292'] = [
    [
        'document' => 'S93324',
        'header_ref' => 'SH54932292',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Easton',
        'ship_to_state' => 'PA',
        'ship_to_ref' => '',
        'qty_ordered' => 13,
        'qty_committed' => 13,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54932293'] = [
    [
        'document' => 'S93325',
        'header_ref' => 'SH54932293',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Burlington',
        'ship_to_state' => 'NJ',
        'ship_to_ref' => '',
        'qty_ordered' => 8,
        'qty_committed' => 8,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54932294'] = [
    [
        'document' => 'S93326',
        'header_ref' => 'SH54932294',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'New Castle',
        'ship_to_state' => 'DE',
        'ship_to_ref' => '',
        'qty_ordered' => 9,
        'qty_committed' => 9,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54932295'] = [
    [
        'document' => 'S93327',
        'header_ref' => 'SH54932295',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'York',
        'ship_to_state' => 'PA',
        'ship_to_ref' => '',
        'qty_ordered' => 25,
        'qty_committed' => 25,
        'warehouse' => 'KENT2',
    ],
];
$order_data['SH54932297'] = [
    [
        'document' => 'S93328',
        'header_ref' => 'SH54932297',
        'status' => 'COMMITTED',
        'date_to_ship' => '12/31/2026',
        'carrier_code' => '',
        'ship_to_name' => 'Amazon.com',
        'ship_to_city' => 'Lakeland',
        'ship_to_state' => 'FL',
        'ship_to_ref' => '',
        'qty_ordered' => 29,
        'qty_committed' => 29,
        'warehouse' => 'KENT2',
    ],
];

$po_index = [];